blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug in the Firebase SDK
    url: https://github.com/firebase/firebase-android-sdk/issues/new/choose
    about: Do you think you have found a bug in the Firebase Android SDK?
  - name: ğŸ¤– MLKit On-Device Issues
    url: https://github.com/googlesamples/mlkit
    about: The MLKit on-device SDK has moved out of Firebase and the best place to get support is on their samples repository.
  - name: ğŸ”¥ Firebase Support
    url: https://firebase.google.com/support/
    about: If you have an urgent issue with your app, please contact support.
